### PR TITLE
Install instructions for Android and Linux

### PR DESCRIPTION
**Pull request by Madis0**
Some easy install instruction links for Android and Linux.

### CODE REVIEW

**Comment by C1710** [comment]
Well, I put it into the Wiki since I put most of the relevant information into it.  
You can see the added page [here](https://github.com/C1710/blobmoji/wiki/Installation-Usage).
But I'll add a link to it on the README later.

**Comment by jingofett** [comment]
The installation guide for android are outdated now

**Comment by C1710** [comment]
> 
> 
> The installation guide for android is outdated now

What exactly is outdated?  
I haven't tried installing it manually in a long time (as I don't use any device with an unlocked bootloader anymore) and I have never tried that Magisk thing 😅

**Comment by jingofett** [comment]
> > The installation guide for android is outdated now
> 
> What exactly is outdated?
> I haven't tried installing it manually in a long time (as I don't use any device with an unlocked bootloader anymore) and I have never tried that Magisk thing 😅

Sorry, the Magisk part is outdated, I haven't tried the manual method. The repo linked under the Magisk instructions is obsolete (it links to another repo which is also obsolete)

**Comment by C1710** [comment]
> 
> 
> > > The installation guide for android is outdated now
> > 
> > 
> > What exactly is outdated?
> > I haven't tried installing it manually in a long time (as I don't use any device with an unlocked bootloader anymore) and I have never tried that Magisk thing 😅
> 
> Sorry, the Magisk part is outdated, I haven't tried the manual method. The repo linked under the Magisk instructions is obsolete (it links to another repo which is also obsolete)

Okay, I've added that to the Wiki.

**Pull request closed without merging**
