### PR TITLE
Change Several Emojis

### PR DESCRIPTION
**Pull request by Bronnel721**
I know you said not to change anymore, but now I'm realizing there's more things that in my opinion look like they don't fit (specifically the emojis that were added in Android Nougat). You've forgot to remove the shiny spot on some buttons, if you didn't know (for example: 🅰,🅱,🆎,🆑,🆒,🆓,🆔,🆕,🆖,🆗,🆘,🆙,🆚,🈁,🈚,🈯,🈵,and🈺), the bald people emojis have no ears, and the people riding a horse emojis are all male. Correct the color palette.

### CODE REVIEW

**Comment by Bronnel721** [comment]
@C1710, what do you think about these changes? I know there's a lot, but I had to change these emojis.

**Comment by Sayhone721** [comment]
@C1710, are these changes good and okay to merge?

**Comment by Sayhone721** [comment]
@C1710, do you think you can merge this PR?

**Comment by Sayhone721** [comment]
Do you think you should merge this PR? What are your thoughts on these designs that I've made?

**Comment by Bronnel721** [comment]
So, do you think that these changes are good? I _hope_ I don't need to add anymore.

**Comment by Bronnel721** [comment]
@C1710, I think I'm done with adding changes for now. If I want to, I would just make another pull request eventually. Also, the neutral-gendered person kneeling emojis aren't in the font, but there are SVGs of them.

**Comment by C1710** [comment]
Sorry, I don't have much time right now to review this PR, so it'll probably take a few weeks until I can give feedback.

**Comment by Bronnel721** [comment]
That's okay, but I do have to say something. In my opinion, your normal color palette should have the values `117, 127, 63`, and have the lighter/darker versions of that color. For the skin tone color palette, the face should get a little darker as the skin got darker, and the opposite should happen for the lighter skin, just like what Google did. (Copy the values of the emojis that have darker and lighter skin tones, and paste them into the code.) You don't have to do it right _now_ though, do it when you feel like it.

**Comment by Bronnel721** [comment]
@C1710, am I allowed to edit the color palette?

**Comment by C1710** [comment]
> @C1710, am I allowed to edit the color palette?

Depends on what exactly. I know it's not perfect, but it shouldn't deviate from the colors that were used in the original set too much.
For example, I would agree that we need some warm brown tone in some cases.

**Comment by Bronnel721** [comment]
If I could edit it, I would put the values `117, 127, 63` for a dark `lime-900`.

**Comment by Bronnel721** [comment]
@C1710, I updated the color palette so that `lime-800` could have the values `141, 148, 58`, and that `lime-900` had the values `117, 127, 63`. Does that sound good?

**Comment by Bronnel721** [comment]
@C1710, if you merge this pull request, make sure to fix the bald emojis because they don't have ears.

**Comment by Secret-chest** [comment]
Make smaller PRs so we can selectively merge them.

**Comment by Bronnel721** [comment]
@Secret-chest, Yeah, I'll try to, but it won't be easy.

**Comment by Bronnel721** [comment]
So, I'm going to open another pull request.

**Pull request closed without merging**
