### PR TITLE
Add smiling_face_with_tear

### PR DESCRIPTION
**Pull request by luisdralves**
This PR adds the [smiling_face_with_tear](https://emojipedia.org/smiling-face-with-tear/) using the [slightly-smiling-face](https://emojipedia.org/slightly-smiling-face/) as base and the tear from [crying-face](https://emojipedia.org/crying-face/)

I hope it is ok

### CODE REVIEW

**Comment by luisdralves** [comment]
It looks like this
image

**Comment by C1710** [comment]
This is the current version: https://github.com/C1710/blobmoji/blob/emoji13/svg13/smiling%20face%20with%20tear.svg

I actually stole your idea with using the slightly-smiling-face mouth 😬

**Comment by C1710** [comment]
Of course, it might be debatable on whether the way I depicted the eyes is okay, when it comes to compatibility.
(It _is_ however semantically correct, at least when looking at the proposal for it)

**Comment by C1710** [comment]
> 
> 
> Of course, it might be debatable on whether the way I depicted the eyes is okay, when it comes to compatibility.
> (It _is_ however semantically correct, at least when looking at the proposal for it)

The reason I chose to do it that way is that otherwise it really looks a bit off, with just a tear floating there on the emoji

**Comment by luisdralves** [comment]
It looks very cool 👌 I actually like the touch on the eyes

**Comment by luisdralves** [comment]
And I'll take this opportunity to thank you for this whole project, the blobs deserve the love

**Pull request closed without merging**
