### PR TITLE
Emoji updates (fixed/color-corrected version of #131)

### PR DESCRIPTION
**Pull request by C1710**
Based on #131, with some fixes, corrected colors

### CODE REVIEW

**Comment by Bronnel721** [comment]
Did you notice that the emoji_u1f3c2 (🏂) emojis with skin tones change the snowboard's color?

**Comment by C1710** [comment]
@Sayhone721 Should I add you to `CONTRIBUTORS_Blob.md` now?

**Comment by Bronnel721** [comment]
Yes, you can.

**Comment by Bronnel721** [comment]
Also, I know you said that I can't change anything, but I tried to make some improvements. Ignore everything, but the blobs.
[Emojis.zip](https://github.com/C1710/blobmoji/files/11907137/Emojis.zip)

**Comment by Bronnel721** [comment]
The yawning face looks stretched.

**Comment by Bronnel721** [comment]
Also, can you please remove the outline in the🥤(`emoji_u1f964.svg`) emoji?

**Pull request merged**
