### PR TITLE
Fix #43

### LINKED ISSUE #43: Add a hand to yawning face
https://emojipedia.org/yawning-face/

🥱 

Definitely would express the meaning better if it had a hand, like other OEMs.

### PR DESCRIPTION
**Pull request by rileyinman**
I redesigned `U+1F971` 🥱 to better match other vendors. Let me know if there are any changes you'd want!

### CODE REVIEW

**Comment by C1710** [comment]
I think there are two issues with that proposal:  
1. The distance between the eyes is a bit too much (which is actually my fault, since the original design looks just as weird in that aspect)
2. I think the eyebrows should not point upwards (if you know what I mean). It somehow looks... I don't know... _arrogant_.

This would be a solution that is more similar to my original design (which indeed is not very similar to the other vendors)  
Another possible design for the yawning emoji

(_Github didn't let me upload the SVG file, so I rendered it into a PNG_)

**Comment by rileyinman** [comment]
@C1710 I see what you mean about the possibly arrogant look... it 's probably not a good fit. I think your new one would have the same meaning as other vendors even if it looks a bit different. The hand does look a bit odd to me though, like all fingers but the pinky and thumb have too thick an outline?

**Comment by C1710** [comment]
That was an attempt to make it look a bit more like the 🤗 hands. But it's easily reversible.

**Comment by rileyinman** [comment]
Sorry, I forgot to answer this :sweat_smile: I think that version with fixed hands would be perfect, and thanks so much!

**Comment by C1710** [comment]
✅ in c26770ee1f265e20dae9c4a4729519eadc3c2ca4

**Pull request closed without merging**
