### PR TITLE
Zany face redesign

### PR DESCRIPTION
**Pull request by JCLemme**
zany
Not sure if I'm done with this one but I think it's an improvement over the current design. I copied the color and shape of the tongue from other blob emojis, removed the teeth in the mouth (which seemed to clash with the rest of the face), and converted the eyes to regular, pupil-less blob eyes.

### CODE REVIEW

**Comment by C1710** [comment]
I agree that the teeth can be removed (In my opinion it doesn't make such a difference, but I'm absolutely fine with it).

About the eyes: I'm not sure if it's just an optical illusion, but the right eye looks pretty large which looks rather strange when they are all dark (they begin to look like holes or alien-like eyes).
Just as an exaggerated illustration how the white part matters:
emoji_u1f600_very_creepy
emoji_u1f600_still_creepy
And in the end, eyes including the white part are actually very common both for the Blobs as in other emoji sets (all vendors represented on Emojipedia have the white part included for this particular emoji).

Finally the tongue: That's something I'm also fine with.
Although the shape isn't perfect, the contrast between the tongue and the mouth isn't large enough to actually see something (which is fine, although a brighter version __might__ be better suited in this case as it's (IIRC) the first case where the tongue is not used in conjunction with a closed mouth).

**Comment by JCLemme** [comment]
The whites of the eyes are tough for the Blobs. Too little and they look too realistic for the genericized Blobs; none at all and they look like holes as you said. This face shows it in particular because I made the right eye larger than normal. I'm leaning towards keeping eyes either entirely dark or with plenty of space around the pupil. With that in mind I tweaked the zany face a little:
zany
It borrows the eye proportions from other Blob emojis with pupils. The convention is to make one eye smaller, but I think making the pupils askew represents the idea of "zany" enough for this to not be necessary. Lmk what you think. 

The tongue could be a little brighter; I was keeping the colors matched with other tongues but I agre that it could stand out better here. I'll toy around with it and report back.

**Comment by C1710** [comment]
How about this color: `#EB7AA4`?
emoji_u1f92a

**Comment by JCLemme** [comment]
That color is good.

**Pull request closed without merging**
