### PR TITLE
Change PC emoji to be a laptop, to align to major vendors

### PR DESCRIPTION
**Pull request by Secret-chest**

### CODE REVIEW

**Comment by Secret-chest** [comment]
@C1710 please respond

**Comment by Secret-chest** [comment]
@C1710

**Review by C1710 — APPROVED** [review]

**Comment by C1710** [comment]
I'll add you to [CONTRIBUTORS_Blob](https://github.com/C1710/blobmoji/blob/main/CONTRIBUTORS_Blob.md). Is that alright for you?

**Comment by Secret-chest** [comment]
> I'll add you to [CONTRIBUTORS_Blob](https://github.com/C1710/blobmoji/blob/main/CONTRIBUTORS_Blob.md). Is that alright for you?

Wow, thanks 😉

**Pull request merged**
