### PR TITLE
Tweaks to the freezing face

### PR DESCRIPTION
**Pull request by JCLemme**
icy
I'm not done with this one but I would like suggestions. I changed the mouth to gritted teeth and changed the snowflakes to icicles to better reflect [the standard](https://emojipedia.org/cold-face/).

### CODE REVIEW

**Comment by JCLemme** [comment]
icy
Another tweak. I'm leaning towards fewer icicles.

**Comment by C1710** [comment]
Personally I'm not a big fan of this icicle design (not specific to your proposal), as it looks kinda strange.
However I do agree that there are some issues with the current design as the snowflakes are barely visible on a light background and look a bit strange.
One solution might be to use fewer and larger (and non-circular) snowflakes like Google does...

**Comment by JCLemme** [comment]
Yeah the icicles aren't very good. Snowflakes seem the better option. The convention is to use icicles but I don't mind breaking from convention if it won't mess with the meaning of the emoji, and I can't really think of a reason to need icicles over something else that means "cold".

I'll mock something up and update this in a couple of days.

**Comment by C1710** [comment]
Quick question: Did you remove the gradient or did you want to remove it?
Here in the browser, it's all blue, but if I open the file in Affinity Designer (not Inkscape) it still has the same gradient as the old version 🤔

**Comment by C1710** [comment]
Here's a variant that has a new gradient and a smaller mouth:
emoji_u1f976

(I tried to create a pull request to your fork, but Github returned a 404 error 🤷‍♀️)

[emoji_u1f976.zip](https://github.com/C1710/blobmoji/files/4311565/emoji_u1f976.zip)

**Comment by JCLemme** [comment]
icy
Snowflakes copied from another Blob emoji. I think the whole thing should be blue; all the other emoji sets use a solid blue emoji. Not sure about the gradient showing up tho, that could be an issue. I'm using Inkscape

**Comment by C1710** [comment]
The one scheduled for the Emoji 13.0 release is now very similar to your design. Do you think it's good like this?

https://github.com/C1710/blobmoji/blob/emoji13/svg/emoji_u1f976.svg

**Comment by C1710** [comment]
I think I'll close this for now...

**Pull request closed without merging**
